; Ventec Systems - Carte de monitoring AGV
; Framework Arduino sur ESP32 (PSRAM requis pour alarmes EXF-25)

[env:ventec_monitor]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.2
    adafruit/Adafruit INA219@^1.2.3
    adafruit/Adafruit TMP117@^1.0.2
    adafruit/Adafruit LIS3DH@^1.2.4
    adafruit/Adafruit SHT31 Library@^2.2.2
    adafruit/RTClib@^2.1.4
